language: go
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_cache:
- rm -rf $GOPATH/src/github.com/${TRAVIS_REPO_SLUG}/*
- rm -rf $GOPATH/pkg/**/github.com/${TRAVIS_REPO_SLUG}
cache:
  directories:
    - $GOPATH/src
    - $GOPATH/pkg
before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
install:
  - go get -t ./...
services:
  - redis-server
script:
  - go test -v ./...
go:
  - 1.6.4
  - 1.7.5
  - 1.8
  - 1.9.2
